name: GitHub Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      # Stats gerais
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: mluizuliana
          template: classic
          base: header, activity, community
          filename: metrics.svg

      # Top Languages
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: mluizuliana
          template: classic
          base: ""
          languages: yes
          languages_details: bytes-size, percentage
          languages_limit: 6
          filename: languages.svg
