name: GitHub Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: mluizuliana

          # ⚠️ NÃO esconder base
          template: terminal
          base: ""

          # 🔥 LANGUAGES (obrigatório assim)
          languages: yes
          languages_limit: 5
          languages_details: percentage
          languages_threshold: 0%
